apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 272562860760.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 272562860760.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: 0ccb5b3b
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
